function createfigure1(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 28-May-2019 10:08:52

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Marker','o','LineWidth',2,'Parent',axes1);
set(plot1(1),'DisplayName','\phi_0 = 90°','LineWidth',3,'Color',[0 0 0]);
set(plot1(2),'DisplayName','\phi_0 = 75°',...
    'Color',[0.501960784313725 0.501960784313725 0.501960784313725]);
set(plot1(3),'DisplayName','\phi_0 = 60°','LineStyle','-.',...
    'Color',[0.650980392156863 0.650980392156863 0.650980392156863]);
set(plot1(4),'DisplayName','\phi_0 = 45°','LineWidth',1,'LineStyle','--',...
    'Color',[0.650980392156863 0.650980392156863 0.650980392156863]);
set(plot1(5),'DisplayName','\phi_0 = 0°','LineStyle',':','Color',[0.8 0.8 0.8]);

% Create ylabel
ylabel('N_e/N_{MC} [%]');

% Create xlabel
xlabel('SNR [dB]');

% Create title
title('Estimation of \tau');

box(axes1,'on');
% Create legend
legend(axes1,'show');

