function [F,Mag,Fase] = DSS(F1, F0, AnalysisCycles, fs,  Signal)
NSamples = length(Signal);
Signal_A = Signal(1:NSamples/2);
Signal_B = Signal(NSamples/2-1:end);

%%%%% Adjacent window calculation
    SignalParams(1) = F1; SignalParams(2:8) = 0;
    DelayCorr = 0; %-3500.0; %   %[in nanosecond]
    MagCorr = 1;
    
    [Synx_aw,Freq_aw,ROCOF_aw] = SteadyStateFit ( ...
	SignalParams, ...
	DelayCorr, ...
	MagCorr, ...
	F0, ...
	AnalysisCycles, ...
	fs, ...
	Signal_A ...
);
        
[Synx_bw,Freq_bw,ROCOF_bw] = SteadyStateFit ( ...
	SignalParams, ...
	DelayCorr, ...
	MagCorr, ...
	F0, ...
	AnalysisCycles, ...
	fs, ...
	Signal_B ...
);

F = mean([Freq_aw,Freq_bw]); % in Hz
Mag = abs(Synx_aw);
dt = 1/fs; T = NSamples*dt;
corr_fase = -90; % in deg;
Fase = angle(Synx_aw)*180/pi + corr_fase; % in degrees